### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [legianni/CMPE131-Project#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by realCalvin** [comment]
Group #3, Class Section 1
Calvin Ly

**Comment by legianni** [comment]
Group number 3 and class section 1
Ecolo-Gianni Lebumfacil

**Comment by miamore287** [comment]
Group number 3 and class section 1
Bhavana Mahendraker

**Comment by ProfRojas** [comment]
Please have all of your teammates respond. Otherwise, you will only receive partial credit for the GitHub portion.

**Comment by nikkomdoza** [comment]
Group number 3 and class section 1.

**Comment by ProfRojas** [comment]
Thanks!

**Comment by miamore287** [comment]
Hi Bhavana Mahendraker. Team 3 section 1

**Comment by miamore287** [comment]
Hi Professor,

Did you want us to reply on email or in GitHub? I thought that I just had
to reply on github. So i didnt reply here?
